name: Shit Programmers Say
description: What Is nekova Made Of?
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

github: shit-programmers-say.github.io
permalink: /:title

#Details for the RSS feed generator
url:            'blog url'
author:         'nekova'
