name: Shit Programmers Say
description:
meta_description: "Hello, world!"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

github: shit-programmers-say.github.io
permalink: /:title
url: http://blog.nekova.net

#Details for the RSS feed generator
url:            'blog.nekova.net'
author:         'nekova'
